### ISSUE TITLE
大佬有空做一个fgo日历吗

### ISSUE THREAD

**Issue by fack-A2Z** [NepPure/bh3_calendar#1]

**Comment by NepPure** [comment]
有合适的数据源可以趴吗

**Comment by fack-A2Z** [comment]
> 有合适的数据源可以趴吗

像fgowiki或是mooncell这种可以吗

**Comment by NepPure** [comment]
需要扒网页比较麻烦

PCR和崩3之类的能找到类似这种的数据

https://mahomaho-insight.info/cached/gameevents.json

如果你知道相关的可以联系我

**Comment by NepPure** [comment]
我去试试扒官网新闻

**Comment by NepPure** [comment]
https://github.com/NepPure/fgo_calendar
